---
releases:
- name: datadog-agent
  sha1: 573bed2ab7960eb97dafff4b7c6111e7ad72b39c
  url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-agent-0.1.5.tgz
  version: 0.1.5

properties:
  api_key: (( grab $DATADOG_API_KEY || "undefined" ))
  include_bosh_tags: true
  bosh_tags_prefix: ""
  tags:
    env: bosh-lite
