---
releases:
- name: datadog-agent
  sha1: 14c7f9be2eb534fda1f4c70ea2355865ac93a87b
  url: https://github.com/alphagov/paas-datadog-agent-boshrelease/releases/download/v5.8.5.3-gds/datadog-agent-v5.8.5.3-gds.tgz
  version: "v5.8.5.3-gds"

properties:
  api_key: (( grab $DATADOG_API_KEY || "undefined" ))
  include_bosh_tags: true
  bosh_tags_prefix: ""
  tags:
    env: bosh-lite
