---
name: (( concat "datadog-for-cloudfoundry-" $DEPLOY_ENV || "undefined" ))
director_uuid: (( grab $BOSH_UUID || "c9ff6012-3899-4540-bca1-77e05f5a32d0" ))

releases:
- name: datadog-for-cloudfoundry
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.10.10/28
    reserved: [10.244.10.1]
    static:
    - 10.244.10.2
    - 10.244.10.4
    - 10.244.10.6
    - 10.244.10.8
    - 10.244.10.10
    - 10.244.10.12
    - 10.244.10.14
    cloud_properties:
      name: random
    dns:
    - 8.8.4.4

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 10000-300000
  max_in_flight: 2

jobs:
- name: cell
  templates:
  - name: rep
    release: diego
  - name: garden
    release: garden-runc
  - name: consul_agent
    release: consul
  - name: cflinuxfs2-rootfs-setup
    release: cflinuxfs2-rootfs
  - name: datadog-agent
    release: datadog-agent
  - name: datadog-rep
    release: datadog-for-cloudfoundry
  - name: datadog-garden
    release: datadog-for-cloudfoundry
  - name: datadog-consul
    release: datadog-for-cloudfoundry
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.10.2
  properties:
    consul:
      agent:
        mode: server

# Postgresql is only required for Cloud Controller to start.
# It must be in a different "job" because it must provisioned first.
- name: postgresql
  templates:
  - name: postgres
    release: postgres
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.10.4

- name: api
  templates:
  - name: cloud_controller_ng
    release: capi
  - name: datadog-agent
    release: datadog-agent
  - name: datadog-cc
    release: datadog-for-cloudfoundry
  - name: datadog-cc-worker
    release: datadog-for-cloudfoundry
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.10.6

- name: router
  templates:
  - name: nats
    release: nats
  - name: gorouter
    release: routing
  - name: datadog-agent
    release: datadog-agent
  - name: datadog-nats
    release: datadog-for-cloudfoundry
  - name: datadog-router
    release: datadog-for-cloudfoundry
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.10.8

- name: diego
  templates:
  - name: route_emitter
    release: diego
  - name: consul_agent
    release: consul
  - name: datadog-agent
    release: datadog-agent
  - name: datadog-route-emitter
    release: datadog-for-cloudfoundry
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.10.10
  properties:
    consul:
      agent:
        mode: server

